@baseUrl = https://8080-lucastamagaw-aula022024-nw4s5i0s73l.ws-us115.gitpod.io

###
GET {{baseUrl}}/alunos

###
POST {{baseUrl}}/alunos
Content-Type: application/json

{
    "nome": "Lucas Tamura"
}

###

GET {{baseUrl}}/alunos/1
Content-Type: application/json

###
PUT {{baseUrl}}/alunos/1
Content-Type: application/json

{
    "nome": "Nome de Teste"
}

###
DELETE {{baseUrl}}/alunos/1